repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    # - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-json
    - id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
