repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
      exclude: generated/
    - id: end-of-file-fixer
      exclude: generated/
    - id: check-yaml
      exclude: generated/
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-json
    - id: requirements-txt-fixer
    - id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    #- id: terraform_tfsec
    #  files: ^infra/cloud/aws/
